server:
  port : 4000
spring:

  jpa:
#    database: MYSQL
#    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB10Dialect
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
#    url: jdbc:mariadb://host.docker.internal:3306/hansoom?useSSL=false
#    url: jdbc:mariadb://localhost:3306/hansoom?useSSL=false
#    url: jdbc:mariadb://sml.synology.me:3306/hansoom?useSSL=false
#    url: jdbc:mariadb://118.38.168.239:3306/hansoom?useSSL=false

#    url: jdbc:mariadb://172.30.1.80:3306/hansoom?useSSL=false
#    username: kukirun
#    password: Abcde123!@#
    
    url: jdbc:mariadb://localhost:3306/hansoom?useSSL=false
    username: root
    password: Abcde123!@#
    
#    url: jdbc:mysql://kukirundb01.caxapjytxuey.ap-northeast-2.rds.amazonaws.com:3306/hansoom?useSSL=false
#    username: kukirun
#    password: dkakwhsznzl23
  